services:
  scraper:
    build: .
    container_name: linkedin_scraper_v2
    restart: always
    ports:
      - "5005:5000"
    volumes:
      - ./linkedin_session:/app/linkedin_session
      - ./scraped_data:/app/scraped_data
    environment:
      - PORT=5000
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=changeme_securely
      - HEADLESS=true
    shm_size: '512mb' # Use /tmp instead (via disable-dev-shm-usage) to save RAM
